#! /usr/bin/env ruby

require 'usdt'
STDOUT.sync = true

provider = USDT::Provider.new("test")
probe = provider.add_probe("testProbe", USDT::ARG_UINT32, USDT::ARG_UINT64)
provider.load

puts 'ready'

if count = ARGV.first
    Integer(count).times do |i|
        probe.fire(i + 100, i)
    end
else
    i = 0
    loop do
        probe.fire(i + 100, i)
        i += 1
    end
end
