#! /usr/bin/env ruby

require 'usdt'
STDOUT.sync = true

provider = USDT::Provider.new("test")
probe = provider.add_probe("testProbe")
provider.load

puts 'ready'

if count = ARGV.first
    Integer(count).times do |i|
        puts "enabled" if probe.enabled?
        puts "fired" if probe.fire
    end
else
    loop do
        puts "enabled" if probe.enabled?
        puts "fired" if probe.fire
    end
end
