#! /usr/bin/env ruby

require 'usdt'
STDOUT.sync = true

provider = USDT::Provider.new("test")
probe = provider.add_probe("testProbe", Float)
provider.load

puts 'ready'

loop do
    probe.fire(Float(ARGV[0]))
end
